name: nuget_push

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run : dotnet restore ffi/cs/bls.sln
      
      - name : Build
        run : dotnet build --configuration Release --no-restore ffi/cs/bls.sln
      
      - name : Test
        run : dotnet test --configuration Release --no-build ffi/cs/bls.sln

      - name : Pack
        run : dotnet pack ffi/cs/bls.sln

      - name: Push
        run : dotnet nuget push bin/*.nupkg -k $NUGET_API_KEY -n -s https://api.nuget.org/v3/index.json